/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.study21.jcsv.xxl.app;

public class App {
    public static void main(String[] args) {
        System.out.println("hello");
    }
}
