/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.study21.jcsv.xxl.app;

import org.junit.jupiter.api.Test;
import picocli.CommandLine;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ArgumentsTest {
    @Test
    void testJustCommand() {
        List.of("cut", "sort", "sed", "awk").forEach(s -> {
            Arguments arguments = CommandLine.populateCommand(new Arguments(), new String[] {s});
            assertEquals(s, arguments.command);
        });
    }
}
