/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.study21.jcsv.xxl.common;

public interface CSVMeta {
    boolean hasHeader();
    int columnsNumber();
    String columnName(int i);
}
